/*
===============================================================================

    DroneVoice.h
    Author: Harry Moss
    Created: 29th May 2024

    Realtime drone voice DSP engine for Tarini.

    Each DroneVoice represents one string of the Tanpura — it generates a
    continuous tone using additive synthesis (fundamental + harmonics),
    applies LFO-based pitch drift to simulate natural string intonation,
    and passes the result through a bandpass filter to model body resonance.

    Design principle: this class is completely self-contained and stateless
    beyond its own phase accumulators. It has no knowledge of JUCE's plugin
    infrastructure, no UI dependencies, and no dynamic allocation. This makes
    it directly portable to future embedded (ARM Cortex-M) targets.

===============================================================================
*/

#pragma once

// JuceHeader.h is generated by CMake (juce_generate_juce_header) at configure
// time. It pulls in all JUCE modules declared in CMakeLists.txt. You will not
// find this file in the source tree — it lives in build/Tarini_artefacts/.
#include <JuceHeader.h>

class DroneVoice
{
public:
    // Explicitly defaulted constructor required by MSVC when
    // JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR is present.
    // Without this, MSVC refuses to default-construct the voices[4] array
    // in TariniAudioProcessor because the macro implicitly deletes some
    // special member functions, confusing the compiler's implicit constructor
    // generation rules.
    DroneVoice() = default;

    // Called once before audio starts, from TariniAudioProcessor::prepareToPlay.
    // This is where ALL initialisation that depends on sampleRate happens.
    // Rule: never allocate or initialise in process() — only here.
    void prepare(double sampleRate);

    // Set the fundamental frequency of this voice in Hz.
    // Called from TariniAudioProcessor::updateVoices() at the start of each
    // processBlock, picking up any tonic parameter changes from the UI.
    void setFrequency(float f);

    // Set the output gain scalar for this voice (0.0 – 1.0 range).
    // Each of the four Tanpura strings has a slightly different level
    // to match the acoustic balance of the real instrument.
    void setGain(float g);

    // Called once per sample from TariniAudioProcessor::processBlock.
    // Advances all phase accumulators, computes one sample of additive
    // synthesis, applies the bandpass filter, and returns the result.
    // Must be realtime-safe: no allocation, no locks, no blocking calls.
    float process();

private:
    // ── DSP state ─────────────────────────────────────────────────────────

    // Current fundamental frequency in Hz. Set via setFrequency().
    float frequency = 220.0f;

    // Output gain scalar for this voice. Set via setGain().
    float gain = 0.2f;

    // Main oscillator phase accumulator, in radians [0, 2π).
    // Incremented every sample by phaseInc = (frequency / sampleRate) * 2π.
    // Wraps at 2π to prevent unbounded growth and floating-point precision loss.
    float phase = 0.0f;

    // LFO phase accumulator, in radians [0, 2π).
    // Advances at lfoIncrement radians per sample (~0.1 Hz).
    float lfoPhase = 0.0f;

    // LFO phase increment per sample — computed once in prepare() as:
    //   (0.1 / sampleRate) * 2π
    // Computing it this way makes the LFO rate sample-rate-independent:
    // the drone drifts at 0.1 Hz whether running at 44100, 48000, or 96000 Hz.
    float lfoIncrement = 0.0f;

    // Stored sample rate, set in prepare(). Used in process() to convert
    // frequency (Hz) into a per-sample phase increment (radians/sample).
    double currentSampleRate = 44100.0;

    // ── JUCE DSP filter ───────────────────────────────────────────────────

    // State Variable TPT (Topology-Preserving Transform) filter.
    // TPT means the digital implementation preserves the topology of the
    // analogue prototype circuit — this gives excellent numerical stability
    // at low sample rates, making it a good choice for future embedded targets.
    // Configured as a bandpass at 900 Hz with Q = 0.4 in prepare() to model
    // the resonant body of the Tanpura.
    juce::dsp::StateVariableTPTFilter<float> filter;

    // ── JUCE housekeeping ─────────────────────────────────────────────────

    // Deletes the copy constructor and copy-assignment operator (a DroneVoice
    // should never be copied — it holds live DSP state), and registers this
    // class with JUCE's leak detector so a warning is printed if any instance
    // is not cleaned up before the app exits.
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(DroneVoice)
};